language: node_js
branches:
  only:
    - master
install: npm i
script: npm run coverage && npm run compile
deploy:
  provider: npm
  email: tom@tomruttle.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
