language: node_js
install: npm i
script: npm run coverage && npm run compile
jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: NPM Release
      script: echo "Deploying to NPM ..."
      deploy:
        provider: npm
        email: tom@tomruttle.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
