// flow-typed signature: b7feb12fb82a3dd0bf30a55894a3b184
// flow-typed version: <<STUB>>/window-stub_v0.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'window-stub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'window-stub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'window-stub/es5/window-stub' {
  declare module.exports: any;
}

// Filename aliases
declare module 'window-stub/es5/window-stub.js' {
  declare module.exports: $Exports<'window-stub/es5/window-stub'>;
}
declare module 'window-stub/index' {
  declare module.exports: $Exports<'window-stub'>;
}
declare module 'window-stub/index.js' {
  declare module.exports: $Exports<'window-stub'>;
}
