// flow-typed signature: 1eca9978f4480cf51c517b573336814e
// flow-typed version: <<STUB>>/html5-history_v^0.1.5/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html5-history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html5-history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html5-history/html4' {
  declare module.exports: any;
}

declare module 'html5-history/lib/adapter' {
  declare module.exports: any;
}

declare module 'html5-history/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html5-history/html4.js' {
  declare module.exports: $Exports<'html5-history/html4'>;
}
declare module 'html5-history/index' {
  declare module.exports: $Exports<'html5-history'>;
}
declare module 'html5-history/index.js' {
  declare module.exports: $Exports<'html5-history'>;
}
declare module 'html5-history/lib/adapter.js' {
  declare module.exports: $Exports<'html5-history/lib/adapter'>;
}
declare module 'html5-history/test/index.js' {
  declare module.exports: $Exports<'html5-history/test/index'>;
}
