// @flow

export const DEFAULT_TIMEOUT = 4000;
export const DOM_CHECK_INTERVAL = 100;

const APP_MANAGER_NAMESPACE = 'am';

export const statuses = {
  DEFAULT: 'DEFAULT',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  UNINITIALISED: 'UNINITIALISED',
};

export const levels = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
};

export const eventTitles = {
  WINDOW_BEFORE_UNLOAD: `${APP_MANAGER_NAMESPACE}-beforeunload`,
  HISTORY_POP_STATE: `${APP_MANAGER_NAMESPACE}-popstate`,
  HISTORY_REPLACE_STATE: `${APP_MANAGER_NAMESPACE}-replacestate`,
  HISTORY_PUSH_STATE: `${APP_MANAGER_NAMESPACE}-pushstate`,
  HISTORY_STATE_CHANGE: `${APP_MANAGER_NAMESPACE}-statechange`,
  STATUS_CHANGE: `${APP_MANAGER_NAMESPACE}-statuschange`,
  STATE_CHANGE_BEGIN: `${APP_MANAGER_NAMESPACE}-statechange-begin`,
  STATE_CHANGE_END: `${APP_MANAGER_NAMESPACE}-statechange-end`,
  ERROR: `${APP_MANAGER_NAMESPACE}-error`,
  EXTERNAL_LINK: `${APP_MANAGER_NAMESPACE}-external-link`,
};
