// @flow

export const IMPORT_TIMEOUT = 4000;
export const DOM_CHECK_INTERVAL = 100;

const HISTORY_CALLBACK_NAMESPACE = 'hc';

export const eventTitles = {
  HALTED: `${HISTORY_CALLBACK_NAMESPACE}-halted`,
  ERROR: `${HISTORY_CALLBACK_NAMESPACE}-error`,
  WARNING: `${HISTORY_CALLBACK_NAMESPACE}-warning`,
  WINDOW_BEFORE_UNLOAD: `${HISTORY_CALLBACK_NAMESPACE}-beforeunload`,
  HISTORY_POP_STATE: `${HISTORY_CALLBACK_NAMESPACE}-popstate`,
  HISTORY_REPLACE_STATE: `${HISTORY_CALLBACK_NAMESPACE}-replacestate`,
  HISTORY_PUSH_STATE: `${HISTORY_CALLBACK_NAMESPACE}-pushstate`,
  HISTORY_STATE_CHANGE: `${HISTORY_CALLBACK_NAMESPACE}-statechange`,
  INITIALISE: `${HISTORY_CALLBACK_NAMESPACE}-initialise`,
};

export const statuses = {
  DEFAULT: 'DEFAULT',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  UNINITIALISED: 'UNINITIALISED',
};

export const levels = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
};
